#!/bin/bash

# original docker push command
echo "!!! overwriting docker push ${IMAGE_NAME}"

push() {
  echo "$ docker push ${DOCKER_REPO}:$1"
  docker push ${DOCKER_REPO}:$1
}

push ${DOCKER_TAG}
push latest

push ${DOCKER_TAG}-fr
push fr
